### ISSUE TITLE
Order of added "elements" through JSONObject.put

### ISSUE THREAD

**Issue by bilak** [stleary/JSON-java#270] opened 2016-08-11 12:38 UTC
Currently final object (JSONObject.toString()) is not sorted in order in which it was constructed. It would be nice to have ability to store elements in order. I mean if I put first element "element2" and second "element1" I would like to see them in this order. For this it could be simple solution to change HashMap to LinkedHashMap, but I don't know if this is the right decision or if there should be one more constructor which will accept the map implementation (or some other parameters which will tell that we want to have final json in order as it was constructed). If you want I can submit PR with change from HashMap to LinkedHashMap.

**Comment by johnjaylward** [comment] 2016-08-11 14:38
This is a duplicate of #270, #228, #210, #66, #43, and #37.

This will not be fixed.

**Closed** 2016-08-15 06:38 UTC
