### ISSUE TITLE
Handling of null-values in JSONObject and XML.toString()

### ISSUE THREAD

**Issue by tobihein** [stleary/JSON-java#429] opened 2018-08-03 09:44 UTC
We have a json-string and want to convert it to a corresponding xml-string. In case, that there are null-values in the json-string, we get an unexpected result

**JSon-String**
```
{
   "myKey": null
}
```

**What we do**
```
String jsonString="{\"myKey\": null}";
final JSONObject jsonObject = new JSONObject( jsonString );
finalString xmlString = XML.toString( jsonObject));
```

**What we get**
`<myKey>null</myKey>`

**What we expect**
`<myKey/>`

Is our expectation correct? If yes, I would do a pull-request and change line 594 in class `XML.java`

**Comment by johnjaylward** [comment] 2018-08-03 12:21
No, in this case it's working as designed. In Javascript and JSON, null is a value (as opposed to undefined). In order to maintain the JSON value of null when converting to XML we output that as  the string "null".

**Comment by tobihein** [comment] 2018-08-03 15:28
Thanks for your quick reply.

So in our case there is no difference in the xml for the input

```{
   "myKey": null,
   "myKey2": "null"
}```

Do you have a suggestion how we can get our expected output?

**Comment by johnjaylward** [comment] 2018-08-03 15:52
hmm, now that I'm looking at the code and the history of it, this may be a bug. At https://github.com/stleary/JSON-java/blob/master/XML.java#L594 you can see a null check for the value. This is the java `null` which this library uses to represent javascript `undefined`. However, there is no further check for the JSON `null`  (https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L165) which has a `toString` method that returns`"null"`. (This is why null is output for your sample JSON. The library internally converts it to that `JSONObject.NULL` object).

In reality, the null check in the `XML` class should never happen since the `JSONObject.put` methods all remove keys with `null` values. Hence, the `keySet` call should never contain values that are JAVA `null`. I feel like the intent of that check was to actually check for JSON null and not JAVA null.

@stleary Let me know your opinion on this. It may be a small tweak we want to make.

**Comment by stleary** [comment] 2018-08-03 15:56
@johnjaylward thanks for investigating. Are you suggesting adding a check for JSON null or replacing the existing check?

**Comment by johnjaylward** [comment] 2018-08-03 15:58
Replacing the existing check with  `JSONObject.NULL.equals(value)`.

**Comment by stleary** [comment] 2018-08-03 17:16
Sounds reasonable, no objection on this end.

**Comment by tobihein** [comment] 2018-08-03 19:55
Thanks, you two. My pull-request would have looked exactly like yours, johnjaylward.

I'm looking forward to the upcomming release.

**Comment by johnjaylward** [comment] 2018-08-03 19:56
I'm still updating it a little due to test failures since we were validating that functionality

**Comment by javadev** [comment] 2018-10-18 07:00
Hi,

It may be a new attribute `<myKey null="true"/>`.

**Comment by tobihein** [comment] 2018-10-30 09:13
@javadev 
For me this isn't an option because I can't change the schema of the output-xml.

We added a workaround in our code. We replace all `JSONObject.NULL` with `""`. But we would still be glad to have this changed in the library.

**Comment by tobihein** [comment] 2018-10-30 11:54
I saw the pull-request https://github.com/stleary/JSON-java/pull/412 for another feature request. Can you imagine to also make the output configurable by an additional parameter to the ` XML.toString`-method? This would avoid a breaking change.

**Comment by stleary** [comment] 2018-10-30 14:40
#412 is a good idea. I will proceed with integrating with the unit tests and getting it committed. A section has been added to the Wiki FAQ that addresses how XML requests will be handled going forward.
https://github.com/stleary/JSON-java/wiki/FAQ#status-of-the-xml-code

**Closed** 2018-12-09 01:33 UTC
