### ISSUE TITLE
JSONArray has a bug when calling addAll with a collection (infinite recursion)

### ISSUE THREAD

**Issue by jacob-wieland-gematik** [stleary/JSON-java#901] opened 2024-07-15 12:33 UTC
In Line 1913, the jsonParserConfiguration needs to be passed as last argument

**Comment by stleary** [comment] 2024-07-15 18:35
@jacob-wieland-gematik Can you provide an example of this bug? 
What version are you using? The referenced line number, 1913, does not match the latest JSONArray code.

**Comment by hexetia** [comment] 2024-10-05 14:33
I found this problem yesterday while upgrading from version 20231013 to 20240205.
In PR https://github.com/stleary/JSON-java/pull/823 a regression was introduced with the addition of more parameters to the function [addAll](https://github.com/stleary/JSON-java/pull/823/files#diff-fec26d6d9d923315c17c0bef371ffe219fbcd3c025232be18aaaefec838a4d77R1834), the call to it in the function in the addition in the method [addAll from collection](https://github.com/stleary/JSON-java/pull/823/files#diff-fec26d6d9d923315c17c0bef371ffe219fbcd3c025232be18aaaefec838a4d77R1939) did not contemplate the inclusion of all the new parameters.
![image](https://github.com/user-attachments/assets/d7e05527-76b4-4026-b38e-1a8492f4f419)

**Comment by stleary** [comment] 2024-10-05 15:27
@hexetia Thanks for the info and analysis. Will look into this.

**Comment by stleary** [comment] 2024-11-10 23:58
Closing due to fixed in #907. Will be merged after 3-day window.

**Closed by stleary** 2024-11-10 23:58 UTC
