### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by spectejb** [stleary/JSON-java#331] opened 2017-04-17 18:55 UTC
@stleary - I noticed that you identified the MIT license for this OSS.  Would you mind updating it to reflect that it is licensed under the JSON license?  Unfortunately, there is a big difference between the MIT and JSON licenses based on the "The Software shall be used for Good, not Evil." line.  (I wish the license was MIT... that would make things a lot easier!)

**Comment by stleary** [comment] 2017-04-17 19:22
Thanks for asking, but the current license was chosen by the library author. My agreement to manage the project does not include changing the license. I added an entry to the project Wiki FAQ page to clarify this.

**Comment by johnjaylward** [comment] 2017-04-17 19:57
@stleary , the submitter is talking about this MIT and wondering if it can be changed to the correct license

![screenshot_20170417-155540](https://cloud.githubusercontent.com/assets/383703/25102449/86e1c120-2386-11e7-83f8-0d40f305143d.png)

**Comment by stleary** [comment] 2017-04-17 21:11
Ah, maybe I misunderstood. You think the OP is asking to not declare the MIT license for the project and instead reference the license at http://www.json.org/license.html, which matches the README and source file comments? If so, I am not sure that is even possible. But if you have suggestions on how to do it, let me know and I can ask Douglas.

**Comment by johnjaylward** [comment] 2017-04-17 22:18
Looks like it was autodetected as MIT. Seems we would have to request the custom license to be added. 

https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by johnjaylward** [comment] 2017-04-17 22:20
Looking at the requirements for adding a license,  it doesn't look like this will happen. The best option may be to request a feature with github to allow overriding the autodetected license since it's wrong.

**Comment by spectejb** [comment] 2017-04-18 00:00
@johnjaylward - Thanks for the follow-up and also the additional research re: how to ensure the correct license is reflected.

**Comment by stleary** [comment] 2017-04-18 02:51
It appears that the license image is a feature recently added to GitHub. See https://github.com/blog/2252-license-now-displayed-on-repository-overview. Based on some quick experiments, I think it requires a readme and a license file to activate. We have always had a readme. The license was added in #246. The image and extra text when displaying the license is generated by this project: https://github.com/benbalter/licensee. Apparently since our license text is within 95% of the MIT license, it is considered a match.  

Please post if you want to make a case for taking some action on this. Otherwise, the default will be to leave everything in place as it is now.

**Comment by spectejb** [comment] 2017-04-18 11:56
@stleary - I also wanted to thank you for looking into this.  

I do recommend taking action to fix it.  A restriction of use (in this case, software cannot be used for evil) goes against one of the general open source principles and as a result, the JSON license is not recognized as open source by many organizations like GNU Project, Fedora, Google, etc.   

Ultimately, it is up to an individual to decide whether he/she wants to use software but I support making sure he/she has all of the information to make a well-informed decision!  Appreciate the teamwork here, @stleary and @johnjaylward.

**Comment by stleary** [comment] 2017-04-18 13:35
Should be fixed. GitHub support suggested adding some non-empty text to the first line of the license, which seems to be sufficient to prevent a match to the MIT license.

**Comment by spectejb** [comment] 2017-04-18 14:06
Thanks @stleary!

**Comment by johnjaylward** [comment] 2017-04-18 14:09
Confirmed,  I don't see the MIT anymore either.

**Closed** 2017-04-18 21:12 UTC

**Comment by janhoy** [comment] 2017-05-23 20:03
The Apache Software Foundation has now also banned this library, see https://www.apache.org/legal/resolved.html#json due to the non-OSI license. If you want to avoid more developers fleeing, you should consider asking the copyright holder (cannot find from the project who actually holds the ©) to move to a standard OSI license https://opensource.org/licenses

**Comment by koppor** [comment] 2018-02-07 13:43
More readings on the ban: https://wiki.debian.org/qa.debian.org/jsonevil

**Comment by johnjaylward** [comment] 2018-02-07 13:56
We are well aware of the issue and only the original author (Douglas Crockford) is authorized to change it. It's listed as an FAQ:
https://github.com/stleary/JSON-java/wiki/FAQ#can-you-change-the-license-to-remove-the-the-software-shall-be-used-for-good-not-evil-line

**Comment by spectejb** [comment] 2018-02-07 18:06
Is Douglas Crockford the original author of the software or just the license?  An author (e.g. @stleary) can choose any license for his/her software.

**Comment by johnjaylward** [comment] 2018-02-07 18:11
Douglas is the original author of both.

**Comment by koppor** [comment] 2018-02-07 18:27
@spectejb The discussion was made with many people for a long time. Please follow my above link to https://wiki.debian.org/qa.debian.org/jsonevil. This especially links to a petition to ask Douglas for changing the license: https://www.change.org/p/douglas-crockford-remove-the-not-evil-clause-from-your-license-because-it-is-evil-itself

Furthermore, as far as I understand the rights behind a license, *all* contributors have to agree to a license change. German users can read on at [Open Source Software - Rechtliche Rahmenbedingungen der Freien Software](http://www.beck-shop.de/Jaeger-Metzger-Open-Source-Software/productview.aspx?product=14503508). An example to change a license for a whole project can be read there https://github.com/jgrapht/jgrapht/wiki/Relicensing.

**Comment by johnjaylward** [comment] 2018-02-07 18:45
Just as a note, if we followed a similar re-licencing procedure, it would probably require approval from the following people. Some of these contributors may have had their contributions overwritten over the years, but it's probably better just ask them all anyway. (I'm in the list 3 time though... apparently I didn't know how to get my username properly)

> :  git shortlog -s -n
>     84  Sean Leary
>     72  John J. Aylward
>     69  Douglas Crockford
>     22  stleary
>     13  Bence Er<C5><91>s
>      9  Felix Leipold
>      4  Lukas Treyer
>      4  Miguel
>      3  johnjaylward
>      2  John Aylward
>      2  Mads Ager
>      2  Nils Faupel
>      2  Tomas Tulka
>      2  alessandro rao
>      2  guywithnose
>      1  Andrew Fletcher
>      1  Brian Russell
>      1  Jakob Stemberger
>      1  Joe Ferner
>      1  Nicholas Cull
>      1  Philipp Gill<C3><A9>
>      1  Simulant
>      1  Siyuan Ren
>      1  Willem-Jan Zijderveld
>      1  ajayk
>      1  bpieber
>      1  joumar
>      1  skreutzer
>      1  unknown
