### ISSUE TITLE
Compilation warnings in Java 17

### ISSUE THREAD

**Issue by javadev** [stleary/JSON-java#766] opened 2023-09-02 04:47 UTC
```
[INFO] Compiling 42 source files with javac [debug target 1.8] to target/test-classes
Warning:  bootstrap class path not set in conjunction with -source 8
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[307,28] Boolean(boolean) in java.lang.Boolean has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[308,29] Boolean(boolean) in java.lang.Boolean has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[[31](https://github.com/stleary/JSON-java/actions/runs/6007074183/job/16416765888?pr=741#step:5:32)1,27] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[312,30] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[573,28] Boolean(boolean) in java.lang.Boolean has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[574,29] Boolean(boolean) in java.lang.Boolean has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[578,27] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[579,30] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[999,43] Double(java.lang.String) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1009,43] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1013,43] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1015,38] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1262,31] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1263,31] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1716,21] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1717,21] Double(java.lang.String) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1720,125] Double(java.lang.String) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1720,1[37](https://github.com/stleary/JSON-java/actions/runs/6007074183/job/16416765888?pr=741#step:5:38)] Float(float) in java.lang.Float has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1720,97] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1725,149] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[1728,25] Float(float) in java.lang.Float has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2043,24] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2044,24] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2045,24] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2050,29] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2050,45] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2050,61] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2088,22] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2115,24] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2116,24] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2117,24] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2128,29] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2128,45] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONObjectTest.java:[2128,61] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[371,17] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[373,17] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[375,17] Float(float) in java.lang.Float has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[378,17] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[[38](https://github.com/stleary/JSON-java/actions/runs/6007074183/job/16416765888?pr=741#step:5:39)0,17] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[388,17] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[[39](https://github.com/stleary/JSON-java/actions/runs/6007074183/job/16416765888?pr=741#step:5:40)0,17] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[548,17] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[550,17] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[552,12] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[562,17] Float(double) in java.lang.Float has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[564,17] Float(float) in java.lang.Float has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[566,12] Float(float) in java.lang.Float has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[578,17] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[580,12] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[583,17] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[585,17] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[1014,17] Double(double) in java.lang.Double has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[1017,17] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[1019,17] Integer(int) in java.lang.Integer has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[1028,17] Long(long) in java.lang.Long has been deprecated and marked for removal
Warning:  /home/runner/work/JSON-java/JSON-java/src/test/java/org/json/junit/JSONArrayTest.java:[1030,17] Long(long) in java.lang.Long has been deprecated and marked for removal
```

**Comment by johnjaylward** [comment] 2023-09-03 22:39
I believe this is a duplicate of my comment in #746

**Comment by javadev** [comment] 2023-09-08 04:36
I have taken the initiative to prepare a solution. If it meets with your approval, I am ready to present it https://github.com/stleary/JSON-java/pull/769

**Comment by javadev** [comment] 2023-09-13 06:51
➕

**Closed** 2023-09-16 13:31 UTC
