### ISSUE TITLE
XML to JSON conversion does not keep the order of fields

### ISSUE THREAD

**Issue by kovax** [stleary/JSON-java#564] opened 2020-10-01 10:00 UTC
JSONObject uses HasMap internally which does not keep the order of insertion. I suggest to use LinkedHashMap instead. I have tried it on a clone, see link bellow, I can quickly add a test and submit a PR.

https://github.com/stleary/JSON-java/compare/master...kovax:develop

**Comment by johnjaylward** [comment] 2020-10-01 13:02
please see the FAQ : https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects

The use of hashmap will not be changed in this project. The data contract of a JSONObject is that the keys are unordered.

**Comment by kovax** [comment] 2020-10-01 16:33
I do not ask it to be ordered, I ask to keep the order while converting from XML to JSON. You could say my solution is not correct, because it 'breaks' that requirement.

**Comment by stleary** [comment] 2020-10-01 16:49
@kovax sorry, did not intend to close the issue so quickly if you still had something to say about it. Will leave it open for a day or so, in case anyone wants to comment. 

Requests to order JSON objects are common enough that it is included in the Wiki: [https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects](https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects). This request was answered in the negative by the author of this project, and as a matter of policy we don't revisit such requests.

**Comment by johnjaylward** [comment] 2020-10-01 18:26
"keeping" order is still ordered. Some people argue that using a hash map is still "ordered" because the hashes should be fairly unique and maintain order that way, but different version of the JVM may hash the keys differently giving different orders when run on different VMs.

Basically, the "result" we are looking towards with the current implementation is that you can't rely on key order. One example of this random key ordering is the in [Go Lang](https://golang.org). Not only does the [JSON encoder/decoder explicitly randomize](https://github.com/golang/go/issues/27179) the keys, but even their [internal maps specify](https://golang.org/ref/spec#For_range) that the key orders may vary.

We hold onto the HashMap implementation in our library because it gets as close to a random order as possible without having to create our own map implementation.

JSON is not really meant for human consumption. It's made for data interchange between systems, and happens to be a "human readable" format.

If you look at previous tickets requesting to use the [`LinkedHashMap`](https://github.com/stleary/JSON-java/issues?q=is%3Aissue+linkedhashmap), you will see a lot of discussion on why we won't allow it.

**Comment by johnjaylward** [comment] 2020-10-01 18:32
duplicate of #37, #66, #210, #228, #270, #300, #303, #383, #387, #395, #425, #508

**Comment by kovax** [comment] 2020-10-01 20:52
@stleary Thank you indeed. First of all I apologize, I should have read the existing issues first, and I can see that it ordering in JSONObject is a serious matter for you. I personally like this thread the most #425 ;)

So I checked the XMLParser, and I am sure I won't make an attempt to change it to keep the order of fields during XML to JSON conversion. Instead I will make, hopefully not a futile attempt to convince you to accept my proposal, because it would save me a lot of development time. 

So I propose to make the usage of HashMap/LinkedHashMap configurable. Use a java system property and read it in a static initializer and initialize the JSONObject either with HashMap or LinkedHashmap. You can state in the FAQ that all your tests are run using the default configuration (i.e. HashMap) and the usage of LinkedHashMap is discouraged. This way you are faithful to the standard.

Why should you do this? Simply because it is a popular request. I understand that your primary motivation is to provide a reference implementation and as such you need to keep it as close to standard as possible. But in the same time this library is really popular (3801 usage in maven), which means it is used in real projects. And in real projects ordering is important, especially in the GUI. And the biggest use of javascript is in the browser.

I also think the original purpose of JSON has been surpassed by the community. Popular technologies has this tendency, they are used in situation which were never foreseen by the originators. It is possible to argue that they usage is wrong (ie. iterating the fields of the JSON), but somehow it still done, because it is useful.

**Comment by stleary** [comment] 2020-10-06 15:27
Thanks for the comments, closing this issue to align with the original author decision.

**Closed by stleary** 2020-10-06 15:27 UTC
Labels: Active discussion

**Comment by ArindamDutta02082001** [comment] 2024-06-24 07:22
The best solution to this answer if anyone dont want to change the internal implementation of `JSONObject` source code 

is to use the `XMLMapper` and `JSONMapper` through these 2 dependency
```
<dependencies>
   1. 
 <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.13.3</version>  <!-- Use the latest version bro -->
    </dependency>
 2.     
<dependency>
        <groupId>com.fasterxml.jackson.dataformat</groupId>
        <artifactId>jackson-dataformat-xml</artifactId>
        <version>2.13.3</version> <!-- Use the latest version bro -->
    </dependency>
</dependencies>

```

and we can modify the code as

```
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.xml.XmlMapper;

import java.io.File;
import java.io.IOException;

public class XmlToJsonConverter {

    public static void main(String args[]){

        String inputXmlFile = "C://user//your_xml.xml"
        String outputJsonFile = "C://user//your_output_json.json"

        try {
            convertXmlToJson(inputXmlFile, outputJsonFile);
            System.out.println("Conversion completed successfully.");
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("An error occurred during conversion: " + e.getMessage());
        }
    }

    public static void convertXmlToJson(String inputXmlFile, String outputJsonFile) throws IOException {

        // Create XmlMapper and ObjectMapper
        XmlMapper xmlMapper = new XmlMapper();
        ObjectMapper jsonMapper = new ObjectMapper();

        // Read XML file and convert to JsonNode
        JsonNode jsonNode = xmlMapper.readTree(new File(inputXmlFile));

        // Write JsonNode to JSON file
        jsonMapper.writerWithDefaultPrettyPrinter().writeValue(new File(outputJsonFile), jsonNode);
    }
}

```
