### ISSUE TITLE
Performance & Code Style, avoid passing iterators around

### ISSUE THREAD

**Issue by TheMatthew** [stleary/JSON-java#340] opened 2017-05-22 01:16 UTC
Hi,
I have an issue with the JSONObjecy#keys() method. It states it is an iterator, though the name implies it is an access to a collection. I have also noticed that is it used often in a while(iter.hasNext){foo = iter.next; ...) pattern. This is not as optimal as using an enhanced for loop on a JSONObject#keySet(). It is murky as to whether or not I am allowed to contribute code yet, but if you replace all #keys accesses by #keyset for loops you can go from parsing a 2 GB file in 125 seconds to 115. this is not an order of magnitude like @johnjaylward 's #337  patch, but it's still pretty decent.

One could argue the reason for doing the iterator is to avoid issues with concurrent modifications. I would argue that a readwritelock would be a safer approach in general.

Thanks for making such a great product by the way.

**Comment by johnjaylward** [comment] 2017-05-22 01:43
The history of those loops is from pre-java5 when the enhanced for loop was not available. I think they just haven't been updated due to them working and no complaints from performance. I don't think it should be an issue to update these.

**Comment by stleary** [comment] 2017-05-22 02:14
Everyone is welcome to submit pull requests.  Since the project is in maintenance mode, there are limits to what kind of changes are accepted. Every pull request carries a risk of introducing regressions, or negatively impacting existing users.  Please see the FAQ for more information: https://github.com/stleary/JSON-java/wiki/FAQ.

**Comment by johnjaylward** [comment] 2017-05-22 05:00
@stleary, I believe he was implying he wanted permission from his company before spending company time on it.

I opened a PR for the refactor. Let me know if it meets your needs. It's currently based off of Master and not my other PR that is scheduled for merge.

**Comment by stleary** [comment] 2017-05-23 04:03
This issue is addressed in pull request #341. Please post any future comments on that thread.

**Closed by stleary** 2017-05-23 04:03 UTC
