### ISSUE TITLE
Number comparison in JSONObject::similar can be confused by similar numbers

### ISSUE THREAD

**Issue by blalasaadri** [stleary/JSON-java#618] opened 2021-07-26 09:18 UTC
In version 20210307 I have the following two JSONObjects:
```java
JSONObject first = new JSONObject("{\"a\": 1, \"b\": 2, \"c\": 3}");
JSONObject second = new JSONObject("{\"a\": 1, \"b\": 2.0, \"c\": 4}");
```
These should **not** be similar, since the value of `c` is clearly different. However the value of `first.similar(second)` will be `true` because for number fields the logic is 
```java
if (valueThis instanceof Number && valueOther instanceof Number) {
    return isNumberSimilar((Number)valueThis, (Number)valueOther);
}
```
([JSONObject, line 2095](https://github.com/stleary/JSON-java/blob/master/src/main/java/org/json/JSONObject.java#L2095)) rather than
```java
if (valueThis instanceof Number && valueOther instanceof Number) {
    if (!isNumberSimilar((Number)valueThis, (Number)valueOther)) {
        return false;
    }
}
```
so a single number field triggering that comparison will end the loop in which all fields are compared.

(Note: For some objects or on some JVMs, the behaviour may be unpredictable since the order in which the entries are called is not guaranteed to always be the same on a set.)

I'm using the following JDK to test this:
```sh
$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by stleary** [comment] 2021-07-26 13:05
Isn't this fixed in #611?

**Comment by johnjaylward** [comment] 2021-07-26 13:13
Agree, looks like a duplicate of 611

**Comment by stleary** [comment] 2021-07-26 23:13
Should be fixed now.

**Closed by stleary** 2021-07-26 23:13 UTC

**Comment by blalasaadri** [comment] 2021-07-27 07:23
Agreed, thanks!
