### ISSUE TITLE
public static String org.json.XML.toString(Object) produces invalid XML

### ISSUE THREAD

**Issue by ConradMoeller** [stleary/JSON-java#569] opened 2020-10-08 07:16 UTC
{
   "tag":{
      "two":"two",
      "one":1,
      "three":{
         "five":"üäö#+!\"§$%/()=?´`",
         "four":4,
         "six":{
            "seven":{
               "type":"seven",
               "8eight":8
            }
         }
      }
   }
}

The json example generates a xml with element <8eight> but elements with a number are illegal. That causes an error generating a dom from the return value.

**Comment by johnjaylward** [comment] 2020-10-08 15:26
duplicate of #109, #123, #138, #166, #294

This probably won't be changed as noted in the previous issues/PR. Key validation should be handled as a pre-conversion item on the developer side.

**Comment by johnjaylward** [comment] 2020-10-08 15:29
Although, I wouldn't mind implementing the change from #109. It appears to at least notify the developer at runtime that their JSON model does not work for XML.

**Comment by stleary** [comment] 2020-10-08 17:05
@johnjaylward No objection if you want to implement something similar to #109.

**Comment by ConradMoeller** [comment] 2020-10-09 06:47
Thank you for feedback I did not recognize that the issue is known. We will handle that before we use the conversion method by our own (e.g. find and replace with regex).
Ticket could be closed.

**Comment by stleary** [comment] 2020-10-16 16:21
Closed per discussion.

**Closed by stleary** 2020-10-16 16:21 UTC
