### ISSUE TITLE
JSONArray(String source) is not throwing exception when input string is not a json array.

### ISSUE THREAD

**Issue by shawnhe** [stleary/JSON-java#659] opened 2022-01-11 01:30 UTC
example:

JSONArray("[A][B] C");

doesn't throw an exception.

**Comment by johnjaylward** [comment] 2022-01-11 15:59
Correct. You should get a JSONArray with a single string element of "A". The rest of the input is ignored.

**Comment by stleary** [comment] 2022-01-12 01:40
Closing since this is how the code was designed to work.

**Closed by stleary** 2022-01-12 01:40 UTC
